name: Docker Build

on:
  push:
    paths:
      - "docker-compose*.yml"
      - "backend/Dockerfile"
      - "frontend/Dockerfile"
      - "infra/docker/**"
      - "infra/nginx/**"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose config